/**
 * CA Bot — Embed Script
 * Add this to any website for an AI chatbot.
 * Usage: <script src="https://YOUR-DOMAIN/embed/embed.js" data-tenant="TENANT_ID"></script>
 */
(function(){
var S=document.currentScript,T=S.getAttribute('data-tenant'),P=S.getAttribute('data-position')||'right',C=S.getAttribute('data-color')||'#000000',G=S.getAttribute('data-greeting')||'Hi there! 👋 How can I help you today?';
var API=(S.getAttribute('data-api')||window.location.origin)+'/.netlify/functions/chat';
var SID='ca_'+Date.now()+'_'+Math.random().toString(36).substr(2,9);
if(!T){console.error('[CA Bot] Missing data-tenant');return}
var st=document.createElement('style');
st.textContent='.ca-bot *{box-sizing:border-box}.ca-bot-btn{position:fixed;bottom:24px;'+P+':24px;width:60px;height:60px;border-radius:50%;background:'+C+';color:#fff;border:none;cursor:pointer;box-shadow:0 4px 20px rgba(0,0,0,.2);z-index:999999;display:flex;align-items:center;justify-content:center;font-size:28px;transition:transform .2s}.ca-bot-btn:hover{transform:scale(1.1)}.ca-bot-widget{position:fixed;bottom:100px;'+P+':24px;width:360px;max-width:calc(100vw-48px);height:520px;max-height:calc(100vh-140px);background:#fff;border-radius:16px;box-shadow:0 8px 40px rgba(0,0,0,.15);z-index:999999;display:none;flex-direction:column;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}.ca-bot-widget.open{display:flex}.ca-bot-header{background:'+C+';color:#fff;padding:16px 20px;display:flex;align-items:center;justify-content:space-between}.ca-bot-header h3{margin:0;font-size:16px;font-weight:600}.ca-bot-close{background:none;border:none;color:#fff;font-size:20px;cursor:pointer;padding:0;line-height:1;opacity:.8}.ca-bot-close:hover{opacity:1}.ca-bot-msgs{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:8px;background:#f8f9fa}.ca-bot-msg{max-width:85%;padding:10px 14px;border-radius:12px;font-size:14px;line-height:1.5;word-wrap:break-word;animation:fadeIn .3s}.ca-bot-msg.bot{background:#fff;color:#1a1a1a;align-self:flex-start;border-bottom-left-radius:4px;box-shadow:0 1px 3px rgba(0,0,0,.08)}.ca-bot-msg.user{background:'+C+';color:#fff;align-self:flex-end;border-bottom-right-radius:4px}.ca-bot-msg.typing{background:#fff;color:#888;align-self:flex-start;font-style:italic}.ca-bot-input-area{display:flex;padding:12px;border-top:1px solid #eee;background:#fff;gap:8px}.ca-bot-input{flex:1;border:1px solid #ddd;border-radius:8px;padding:10px 14px;font-size:14px;outline:none;font-family:inherit}.ca-bot-input:focus{border-color:'+C+'}.ca-bot-send{background:'+C+';color:#fff;border:none;border-radius:8px;padding:10px 16px;cursor:pointer;font-size:14px;font-weight:600}.ca-bot-send:hover{opacity:.9}.ca-bot-footer{text-align:center;padding:6px;font-size:10px;color:#aaa;background:#f8f9fa;border-top:1px solid #eee}.ca-bot-footer a{color:'+C+';text-decoration:none}@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}@media(max-width:480px){.ca-bot-widget{width:100vw;max-width:100vw;bottom:0;'+P+':0;height:100vh;max-height:100vh;border-radius:0}.ca-bot-btn{bottom:16px;'+P+':16px}}';
document.head.appendChild(st);
var w=document.createElement('div');w.className='ca-bot';
w.innerHTML='<button class="ca-bot-btn" id="cb-btn"><svg viewBox="0 0 24 24" fill="white"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H5.17L4 17.17V4h16v12z"/><path d="M7 9h10v2H7zm0-3h10v2H7zm0 6h7v2H7z"/></svg></button><div class="ca-bot-widget" id="cb-w"><div class="ca-bot-header"><h3 id="cb-title">💬 Support</h3><button class="ca-bot-close" id="cb-x">✕</button></div><div class="ca-bot-msgs" id="cb-msgs"><div class="ca-bot-msg bot">'+G+'</div></div><div class="ca-bot-input-area"><input class="ca-bot-input" id="cb-inp" type="text" placeholder="Type your message..." autocomplete="off"><button class="ca-bot-send" id="cb-send">Send</button></div><div class="ca-bot-footer">Powered by <a href="https://thecapitalacquisition.com" target="_blank">Capital Acquisition</a></div></div>';
document.body.appendChild(w);
var btn=document.getElementById('cb-btn'),wg=document.getElementById('cb-w'),cx=document.getElementById('cb-x'),ms=document.getElementById('cb-msgs'),inp=document.getElementById('cb-inp'),sd=document.getElementById('cb-send');
btn.onclick=function(){wg.classList.toggle('open');if(wg.classList.contains('open'))inp.focus()};
cx.onclick=function(){wg.classList.remove('open')};
function addMsg(t,r){var d=document.createElement('div');d.className='ca-bot-msg '+r;d.textContent=t;ms.appendChild(d);ms.scrollTop=ms.scrollHeight}
function typing(){var d=document.createElement('div');d.className='ca-bot-msg bot typing';d.id='cb-type';d.textContent='Thinking...';ms.appendChild(d);ms.scrollTop=ms.scrollHeight}
function noty(){var e=document.getElementById('cb-type');if(e)e.remove()}
async function sendMsg(){var t=inp.value.trim();if(!t)return;inp.value='';addMsg(t,'user');typing();try{var r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenantId:T,sessionId:SID,message:t})});noty();if(!r.ok){addMsg('Sorry, connection issue. Try again!','bot');return}var d=await r.json();addMsg(d.reply||'Thanks for your message!','bot')}catch(e){noty();addMsg('Sorry, something went wrong. Try again!','bot')}}
sd.onclick=sendMsg;inp.onkeydown=function(e){if(e.key==='Enter')sendMsg()};
})();
